import "server-only";
import {
  chatModel,
  getOpenRouterClient,
  humanizeConcurrency,
  humanizeStyle,
  humanizeTemperature,
  type HumanizeStyle,
} from "@/lib/openrouter";
import type { TextSegment } from "@/lib/extract/segment";
import { dedupeNearDuplicateParagraphs } from "./dedupe";
import { stripForbiddenDashes } from "./sanitize";
import { stripModelEcho } from "./stripEcho";

const BANNED_PHRASES = `BANNED words and phrases — if any appear in your output, rewrite that sentence:
"delve", "delves", "delving", "delved", "it is important to note", "it is worth noting", "it should be noted", "plays a crucial role", "plays a key role", "underscores", "underscoring", "showcases", "highlights the importance", "demonstrates the importance", "in today's world", "in today's rapidly", "in the realm of", "foster", "fostering", "facilitate", "facilitating", "leverage", "leveraging", "navigate the complexities", "navigating", "needless to say", "a nuanced understanding", "a comprehensive understanding", "it is essential to", "it is critical to", "when it comes to", "the fact that", "serves as a", "serves to", "in order to", "with respect to", "with regard to", "as mentioned", "as noted", "as discussed", "as such", "moreover,", "furthermore,", "additionally,", "consequently,", "subsequently,", "in conclusion,", "to summarize,", "in summary,", "overall,", "ultimately,", "significantly,", "notably,", "importantly,".`;

const SHARED_RULES = `Hard rules:
- Keep all facts, numbers, names, dates, quotes, and citations exactly as they appear. Do not invent or add anything.
- Output ONLY the rewritten text. No preamble, no "Here is...", no labels, no markdown fences.
- Do NOT quote or repeat the input before rewriting it.
- Match the spelling locale of the source (British vs American).

Punctuation:
- NEVER use em dash (—) or en dash (–). Use commas, periods, colons, or parentheses.
- Hyphen (-) is fine for compound words or number ranges only.

Structure:
- Keep paragraph breaks exactly as in the source. Do not merge or split paragraphs.`;

const SYSTEM_MINIMAL = `Your job: rewrite the text below so no AI detector flags it. The output must read like it was written by a knowledgeable human, not generated by a language model.

${SHARED_RULES}

${BANNED_PHRASES}

How humans actually write (follow this):
- Sentence length varies wildly. Some sentences are 5 words. Others stretch on for 30 or 40 words because the thought is complicated and needs the space. Then short again.
- Humans start sentences in many ways: with a verb, a qualifier, a place, a name, a number, a question. They do NOT start every sentence with "The", "This", "It is", or "There are".
- Humans use contractions naturally: "it's", "don't", "can't", "that's", "wasn't", "you'd".
- Humans use casual connectives: "But", "And", "So", "Still", "Even so", "That said", "Of course", "In practice", "For one thing", "At the same time".
- Humans sometimes leave a thought slightly unfinished or add a parenthetical aside (like this one) mid-sentence.
- Humans write with concrete nouns and active verbs. They do not stack abstractions.
- Burstiness is key: alternate between complex multi-clause sentences and sharp, blunt ones.`;

const SYSTEM_STANDARD = `Your job: completely rewrite the text below so that AI detectors score it as human-written. Every sentence must be restructured, not just paraphrased word-by-word.

${SHARED_RULES}

${BANNED_PHRASES}

Techniques that make text undetectable:
1. BURSTINESS: AI writes uniform sentence lengths. You must alternate sharply — a 4-word sentence followed by a 40-word one. This is the single biggest signal detectors use.
2. SENTENCE OPENERS: Never start two consecutive sentences the same way. Rotate: subject-first, verb-first, adverb-first, clause-first, question, fragment.
3. CONTRACTIONS: Use them freely — "it's", "doesn't", "weren't", "can't", "that's", "there's", "you'd", "we're".
4. INFORMAL CONNECTIVES: Start sentences with "But", "And", "So", "Still", "Even then", "Of course", "That said", "For one thing", "At its core", "In practice".
5. IMPERFECTION: A slight redundancy, a parenthetical aside, an incomplete list ("...and so on") — these mark human writing. Include them.
6. CONCRETE OVER ABSTRACT: Replace abstract nouns with the actual thing they describe. "The existence of structural barriers" → "the barriers themselves".
7. RESTRUCTURE CLAUSES: Flip subject/object, move subordinate clauses to the front, split compound sentences, combine short choppy ones — do not just swap synonyms.
8. NO THESIS-STATEMENT RHYTHM: Avoid the pattern "X is Y. This means Z. Therefore W." It is the most detected AI structure.

All facts, citations, and claims must stay identical.`;

function systemForStyle(style: HumanizeStyle): string {
  return style === "minimal" ? SYSTEM_MINIMAL : SYSTEM_STANDARD;
}

function userForStyle(
  style: HumanizeStyle,
  contextSummary: string,
  chunk: string,
): string {
  const ctx = contextSummary
    ? `[Prior section context — do not repeat]\n${contextSummary}\n\n`
    : "";
  if (style === "minimal") {
    return `${ctx}Rewrite the passage so it cannot be flagged by AI detectors. Vary sentence lengths, use contractions, start sentences differently, and remove any AI-sounding phrasing. Keep all facts identical. After rewriting, mentally scan for any banned phrases from the list and fix them. Output only the final rewritten text.\n\n<<<\n${chunk}\n>>>`;
  }
  return `${ctx}Rewrite every sentence in this passage from scratch. The goal is a score below 10% on any AI detector. Use varied sentence lengths (some very short, some long), contractions, informal connectives, and restructured clauses. No two consecutive sentences should open the same way. Eliminate every banned phrase. Keep all facts and citations. After writing, do a final check: if any sentence sounds like it came from a language model, rewrite it. Output only the final text.\n\n<<<\n${chunk}\n>>>`;
}

async function rewriteChunk(
  chunk: string,
  contextSummary: string,
  temperature: number,
  style: HumanizeStyle,
): Promise<string> {
  const client = getOpenRouterClient();
  const model = chatModel();
  const completion = await client.chat.completions.create({
    model,
    temperature,
    max_tokens: Math.min(4096, Math.ceil(chunk.length * 1.35) + 200),
    messages: [
      { role: "system", content: systemForStyle(style) },
      {
        role: "user",
        content: userForStyle(style, contextSummary, chunk),
      },
    ],
  });
  const raw = (completion.choices[0]?.message?.content ?? "").trim();
  return stripForbiddenDashes(stripModelEcho(raw));
}

function summarizeForContext(text: string, maxLen = 600): string {
  const t = text.replace(/\s+/g, " ").trim();
  if (t.length <= maxLen) return t;
  return `${t.slice(0, maxLen)}...`;
}

export type HumanizeProgress = {
  current: number;
  total: number;
};

export async function humanizeSegments(
  segments: TextSegment[],
  onProgress?: (p: HumanizeProgress) => void,
  options?: {
    temperature?: number;
    concurrency?: number;
    style?: HumanizeStyle;
  },
): Promise<string> {
  const style = options?.style ?? humanizeStyle();
  const temperature = options?.temperature ?? humanizeTemperature();
  const concurrency = Math.min(
    6,
    Math.max(1, options?.concurrency ?? humanizeConcurrency()),
  );
  const parts: string[] = new Array(segments.length);
  let rolling = "";

  for (let i = 0; i < segments.length; i += concurrency) {
    const slice = segments.slice(i, i + concurrency);
    const context = summarizeForContext(rolling);

    const rewritten = await Promise.all(
      slice.map((seg) => rewriteChunk(seg.text, context, temperature, style)),
    );

    for (let j = 0; j < slice.length; j++) {
      const idx = i + j;
      parts[idx] = rewritten[j];
      rolling = [rolling, rewritten[j]].filter(Boolean).join("\n\n");
    }

    onProgress?.({
      current: Math.min(i + slice.length, segments.length),
      total: segments.length,
    });
  }

  const merged = parts.join("\n\n");
  return dedupeNearDuplicateParagraphs(
    stripForbiddenDashes(stripModelEcho(merged)),
  );
}
